-- Vista: moderazione UGC (richiesta App Store 1.2).
-- - reports: l'utente può segnalare un punto. Lettura solo all'autore della
--            segnalazione (la moderazione lato dashboard usa service role).
-- - blocks:  blocco utente-utente, lista visibile solo a chi ha bloccato.

-- ---------------------------------------------------------------------------
-- reports
-- ---------------------------------------------------------------------------
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users (id) on delete cascade,
  point_view_id bigint not null references public.point_views (id) on delete cascade,
  reason text not null,
  note text,
  created_at timestamptz not null default now()
);

comment on table public.reports is 'Segnalazioni UGC verso un point view.';

create index if not exists reports_pointview_idx
  on public.reports (point_view_id, created_at desc);

create index if not exists reports_reporter_idx
  on public.reports (reporter_id, created_at desc);

alter table public.reports enable row level security;

drop policy if exists "reports_insert_own" on public.reports;
create policy "reports_insert_own"
  on public.reports for insert
  to authenticated
  with check (auth.uid() = reporter_id);

drop policy if exists "reports_select_own" on public.reports;
create policy "reports_select_own"
  on public.reports for select
  to authenticated
  using (auth.uid() = reporter_id);

-- ---------------------------------------------------------------------------
-- blocks
-- ---------------------------------------------------------------------------
create table if not exists public.blocks (
  blocker_id uuid not null references auth.users (id) on delete cascade,
  blocked_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

comment on table public.blocks is 'Blocchi utente-utente (lato client filtra contenuti).';

create index if not exists blocks_blocker_idx on public.blocks (blocker_id);

alter table public.blocks enable row level security;

drop policy if exists "blocks_select_own" on public.blocks;
create policy "blocks_select_own"
  on public.blocks for select
  to authenticated
  using (auth.uid() = blocker_id);

drop policy if exists "blocks_insert_own" on public.blocks;
create policy "blocks_insert_own"
  on public.blocks for insert
  to authenticated
  with check (auth.uid() = blocker_id);

drop policy if exists "blocks_delete_own" on public.blocks;
create policy "blocks_delete_own"
  on public.blocks for delete
  to authenticated
  using (auth.uid() = blocker_id);
