-- Vista: profili utente (1:1 con auth.users) e punti panoramici.
-- Applicato al progetto remoto tramite Supabase MCP (execute_sql) il 2026-05-04.
-- Per nuovi ambienti: eseguire da SQL Editor o `supabase db push`.

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default '',
  created_at timestamptz not null default now()
);

comment on table public.profiles is 'Profilo applicativo collegato a auth.users';

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- ---------------------------------------------------------------------------
-- point_views: se esiste ancora la tabella legacy "Pointview", rinominala
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'Pointview'
  ) and not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'point_views'
  ) then
    alter table public."Pointview" rename to point_views;
  end if;
end $$;

-- Se non esiste né Pointview né point_views, crea point_views da zero
create table if not exists public.point_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null default '',
  region text not null default '',
  city text not null default ''
);

alter table public.point_views
  add column if not exists created_by uuid references public.profiles (id) on delete set null;

alter table public.point_views
  add column if not exists description text;

alter table public.point_views
  add column if not exists latitude double precision;

alter table public.point_views
  add column if not exists longitude double precision;

alter table public.point_views enable row level security;

drop policy if exists "point_views_select_authenticated" on public.point_views;
create policy "point_views_select_authenticated"
  on public.point_views for select
  to authenticated
  using (true);

drop policy if exists "point_views_insert_own" on public.point_views;
create policy "point_views_insert_own"
  on public.point_views for insert
  to authenticated
  with check (auth.uid() = created_by);

drop policy if exists "point_views_update_own" on public.point_views;
create policy "point_views_update_own"
  on public.point_views for update
  to authenticated
  using (auth.uid() = created_by)
  with check (auth.uid() = created_by);

drop policy if exists "point_views_delete_own" on public.point_views;
create policy "point_views_delete_own"
  on public.point_views for delete
  to authenticated
  using (auth.uid() = created_by);

-- ---------------------------------------------------------------------------
-- Trigger: crea riga profiles per ogni nuovo utente in auth.users
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(new.email, '@', 1),
      'User'
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Backfill: utenti già presenti senza riga in profiles
-- ---------------------------------------------------------------------------
insert into public.profiles (id, display_name)
select
  u.id,
  coalesce(split_part(u.email, '@', 1), 'User')
from auth.users u
where not exists (select 1 from public.profiles p where p.id = u.id)
on conflict (id) do nothing;
