-- Nuova esperienza punti panoramici (VistaApp)
-- - Default points "VistaApp" con fallback locale deterministico
-- - Trending/Recent support
-- - Reviews/rating geogated
-- - Servizi in stile Park4Night + workflow segnalazioni (5 report => update)
-- - Premium entitlement ready

alter table public.profiles
  add column if not exists is_premium boolean not null default false;

alter table public.point_views
  add column if not exists source text not null default 'user',
  add column if not exists external_id text,
  add column if not exists seed_rating numeric(2,1),
  add column if not exists seed_rating_count integer not null default 0;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'point_views_source_check'
      and conrelid = 'public.point_views'::regclass
  ) then
    alter table public.point_views
      add constraint point_views_source_check
      check (source in ('user', 'vista_default', 'external_api'));
  end if;
end $$;

create unique index if not exists point_views_source_external_uidx
  on public.point_views (source, external_id)
  where external_id is not null;

create table if not exists public.point_reviews (
  id bigint generated by default as identity primary key,
  point_view_id bigint not null references public.point_views (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  review_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (point_view_id, user_id)
);

create index if not exists point_reviews_point_created_idx
  on public.point_reviews (point_view_id, created_at desc);

create table if not exists public.point_services_catalog (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  icon text not null default 'misc',
  category text not null default 'general',
  is_active boolean not null default true
);

create table if not exists public.point_view_services (
  point_view_id bigint not null references public.point_views (id) on delete cascade,
  service_id bigint not null references public.point_services_catalog (id) on delete cascade,
  status text not null default 'active',
  updated_by uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (point_view_id, service_id)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'point_view_services_status_check'
      and conrelid = 'public.point_view_services'::regclass
  ) then
    alter table public.point_view_services
      add constraint point_view_services_status_check
      check (status in ('active', 'unavailable', 'seasonal'));
  end if;
end $$;

create table if not exists public.point_service_change_reports (
  id bigint generated by default as identity primary key,
  point_view_id bigint not null references public.point_views (id) on delete cascade,
  service_id bigint not null references public.point_services_catalog (id) on delete cascade,
  suggested_status text not null,
  reporter_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (point_view_id, service_id, reporter_id, suggested_status)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'point_service_change_reports_status_check'
      and conrelid = 'public.point_service_change_reports'::regclass
  ) then
    alter table public.point_service_change_reports
      add constraint point_service_change_reports_status_check
      check (suggested_status in ('active', 'unavailable', 'seasonal'));
  end if;
end $$;

create index if not exists point_service_change_reports_lookup_idx
  on public.point_service_change_reports (point_view_id, service_id, suggested_status)
  where processed_at is null;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists point_reviews_touch_updated_at on public.point_reviews;
create trigger point_reviews_touch_updated_at
before update on public.point_reviews
for each row execute function public.touch_updated_at();

create or replace function public.apply_service_report_threshold()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  vote_count integer;
begin
  select count(*)
  into vote_count
  from public.point_service_change_reports r
  where r.point_view_id = new.point_view_id
    and r.service_id = new.service_id
    and r.suggested_status = new.suggested_status
    and r.processed_at is null;

  if vote_count >= 5 then
    insert into public.point_view_services as pvs (
      point_view_id,
      service_id,
      status,
      updated_by,
      updated_at
    )
    values (
      new.point_view_id,
      new.service_id,
      new.suggested_status,
      null,
      now()
    )
    on conflict (point_view_id, service_id) do update
      set status = excluded.status,
          updated_by = null,
          updated_at = now();

    update public.point_service_change_reports
    set processed_at = now()
    where point_view_id = new.point_view_id
      and service_id = new.service_id
      and suggested_status = new.suggested_status
      and processed_at is null;
  end if;

  return new;
end;
$$;

drop trigger if exists point_service_change_reports_threshold on public.point_service_change_reports;
create trigger point_service_change_reports_threshold
after insert on public.point_service_change_reports
for each row execute function public.apply_service_report_threshold();

alter table public.point_reviews enable row level security;
alter table public.point_services_catalog enable row level security;
alter table public.point_view_services enable row level security;
alter table public.point_service_change_reports enable row level security;

drop policy if exists "point_reviews_select_authenticated" on public.point_reviews;
create policy "point_reviews_select_authenticated"
on public.point_reviews for select
to authenticated
using (true);

drop policy if exists "point_reviews_insert_own" on public.point_reviews;
create policy "point_reviews_insert_own"
on public.point_reviews for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "point_reviews_update_own" on public.point_reviews;
create policy "point_reviews_update_own"
on public.point_reviews for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "point_reviews_delete_own" on public.point_reviews;
create policy "point_reviews_delete_own"
on public.point_reviews for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "point_services_catalog_select_authenticated" on public.point_services_catalog;
create policy "point_services_catalog_select_authenticated"
on public.point_services_catalog for select
to authenticated
using (is_active = true);

drop policy if exists "point_view_services_select_authenticated" on public.point_view_services;
create policy "point_view_services_select_authenticated"
on public.point_view_services for select
to authenticated
using (true);

drop policy if exists "point_view_services_upsert_authenticated" on public.point_view_services;
create policy "point_view_services_upsert_authenticated"
on public.point_view_services for all
to authenticated
using (true)
with check (true);

drop policy if exists "point_service_change_reports_select_authenticated" on public.point_service_change_reports;
create policy "point_service_change_reports_select_authenticated"
on public.point_service_change_reports for select
to authenticated
using (auth.uid() = reporter_id);

drop policy if exists "point_service_change_reports_insert_own" on public.point_service_change_reports;
create policy "point_service_change_reports_insert_own"
on public.point_service_change_reports for insert
to authenticated
with check (auth.uid() = reporter_id);

drop view if exists public.point_view_metrics;
create view public.point_view_metrics
with (security_invoker = true)
as
select
  pv.id,
  pv.created_at,
  pv.name,
  pv.region,
  pv.city,
  pv.description,
  pv.latitude,
  pv.longitude,
  pv.created_by,
  pv.image_urls,
  pv.source,
  pv.external_id,
  coalesce(f.favorite_count, 0)::int as favorite_count,
  coalesce(r.reviews_count, 0)::int as reviews_count,
  case
    when coalesce(r.reviews_count, 0) > 0
      then round(r.avg_rating::numeric, 2)
    when pv.seed_rating is not null
      then round(pv.seed_rating::numeric, 2)
    else null
  end as avg_rating,
  case
    when coalesce(r.reviews_count, 0) > 0
      then coalesce(r.reviews_count, 0)
    else coalesce(pv.seed_rating_count, 0)
  end::int as rating_votes_count
from public.point_views pv
left join (
  select point_view_id, count(*) as favorite_count
  from public.favorites
  group by point_view_id
) f on f.point_view_id = pv.id
left join (
  select
    point_view_id,
    count(*) as reviews_count,
    avg(rating)::double precision as avg_rating
  from public.point_reviews
  group by point_view_id
) r on r.point_view_id = pv.id;

insert into public.point_services_catalog (slug, name, icon, category)
values
  ('parking', 'Parcheggio', 'local_parking', 'access'),
  ('wc', 'WC', 'wc', 'comfort'),
  ('water', 'Acqua', 'water_drop', 'comfort'),
  ('picnic', 'Area picnic', 'lunch_dining', 'comfort'),
  ('camping', 'Sosta camper', 'rv_hookup', 'stay'),
  ('wifi', 'Wi-Fi', 'wifi', 'digital'),
  ('viewpoint', 'Belvedere attrezzato', 'photo_camera', 'experience')
on conflict (slug) do update
set
  name = excluded.name,
  icon = excluded.icon,
  category = excluded.category,
  is_active = true;

-- Pulizia vecchi default (created_by null) e reintegro solo dataset VistaApp.
delete from public.point_views
where created_by is null;

with seeded(name, region, city, description, latitude, longitude, external_id, seed_rating, seed_rating_count) as (
  values
    ('Trolltunga Viewpoint', 'Vestland', 'Ullensvang', 'Scogliera iconica sulla valle norvegese.', 60.1241, 6.7403, 'vistaapp-no-trolltunga', 4.8, 1340),
    ('Mirador de San Nicolás', 'Andalusia', 'Granada', 'Vista classica sull''Alhambra al tramonto.', 37.1810, -3.5882, 'vistaapp-es-sannicolas', 4.7, 2120),
    ('Preikestolen', 'Rogaland', 'Stavanger', 'Piattaforma naturale sul Lysefjord.', 58.9863, 6.1902, 'vistaapp-no-preikestolen', 4.8, 1880),
    ('Seceda Panorama', 'Trentino-Alto Adige', 'Ortisei', 'Cresta dolomitica con vista 360 gradi.', 46.6068, 11.7545, 'vistaapp-it-seceda', 4.9, 960),
    ('Rocca Calascio Belvedere', 'Abruzzo', 'Calascio', 'Belvedere medievale nel Parco del Gran Sasso.', 42.3296, 13.6884, 'vistaapp-it-calascio', 4.7, 720),
    ('Cliffs of Moher North Point', 'County Clare', 'Doolin', 'Falesie atlantiche con passerelle panoramiche.', 52.9715, -9.4309, 'vistaapp-ie-moher', 4.8, 3010),
    ('Bastei Aussicht', 'Saxony', 'Lohmen', 'Ponti di roccia e gole dell''Elba.', 50.9638, 14.0729, 'vistaapp-de-bastei', 4.6, 1100),
    ('Cap de Formentor Mirador', 'Balearic Islands', 'Pollença', 'Punto panoramico sul Mediterraneo e Serra de Tramuntana.', 39.9574, 3.2026, 'vistaapp-es-formentor', 4.7, 1430),
    ('Lofoten Reinebringen', 'Nordland', 'Reine', 'Panorama sulle baie artiche delle Lofoten.', 67.9373, 13.0892, 'vistaapp-no-reinebringen', 4.9, 880),
    ('Cinque Terre Corniglia Terrace', 'Liguria', 'Corniglia', 'Terrazza naturale sui borghi delle Cinque Terre.', 44.1209, 9.7089, 'vistaapp-it-corniglia', 4.6, 1540)
)
insert into public.point_views (
  name,
  region,
  city,
  description,
  latitude,
  longitude,
  source,
  external_id,
  seed_rating,
  seed_rating_count,
  created_by
)
select
  s.name,
  s.region,
  s.city,
  s.description,
  s.latitude,
  s.longitude,
  'vista_default',
  s.external_id,
  s.seed_rating,
  s.seed_rating_count,
  null
from seeded s;

insert into public.point_view_services (point_view_id, service_id, status, updated_by)
select pv.id, c.id, 'active', null
from public.point_views pv
join public.point_services_catalog c on c.slug in ('parking', 'viewpoint')
where pv.source = 'vista_default'
on conflict (point_view_id, service_id) do nothing;
